name: Docker Test

on:
  push:
    branches:
      - main
      - test

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t test-docker .

      - name: Run container
        run: docker run --rm test-docker